version: "3"

services:
  # This is container name
  mariadb:
    # This is the image downloaded from docker hub which is running.
    image: "mariadb"
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: equipmentdb
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql